# coding: utf-8

"""
    Ride-Sharing API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from ride_sdk.models.ride_booking import RideBooking
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Ride(BaseModel):
    """
    Ride
    """ # noqa: E501
    driver_name: StrictStr
    total_seats: StrictInt
    pickup_location: StrictStr
    destination: StrictStr
    id: StrictInt
    available_seats: StrictInt
    driver_phone: Optional[StrictStr] = None
    bookings: Optional[List[RideBooking]] = None
    __properties: ClassVar[List[str]] = ["driver_name", "total_seats", "pickup_location", "destination", "id", "available_seats", "driver_phone", "bookings"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Ride from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in bookings (list)
        _items = []
        if self.bookings:
            for _item_bookings in self.bookings:
                if _item_bookings:
                    _items.append(_item_bookings.to_dict())
            _dict['bookings'] = _items
        # set to None if driver_phone (nullable) is None
        # and model_fields_set contains the field
        if self.driver_phone is None and "driver_phone" in self.model_fields_set:
            _dict['driver_phone'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Ride from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "driver_name": obj.get("driver_name"),
            "total_seats": obj.get("total_seats"),
            "pickup_location": obj.get("pickup_location"),
            "destination": obj.get("destination"),
            "id": obj.get("id"),
            "available_seats": obj.get("available_seats"),
            "driver_phone": obj.get("driver_phone"),
            "bookings": [RideBooking.from_dict(_item) for _item in obj["bookings"]] if obj.get("bookings") is not None else None
        })
        return _obj


