# coding: utf-8

"""
    Ride-Sharing API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ride_booking_create import RideBookingCreate

class TestRideBookingCreate(unittest.TestCase):
    """RideBookingCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RideBookingCreate:
        """Test RideBookingCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RideBookingCreate`
        """
        model = RideBookingCreate()
        if include_optional:
            return RideBookingCreate(
                user_name = ''
            )
        else:
            return RideBookingCreate(
                user_name = '',
        )
        """

    def testRideBookingCreate(self):
        """Test RideBookingCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
