# coding: utf-8

"""
    Ride-Sharing API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_book_ride_rides_ride_id_book_post(self) -> None:
        """Test case for book_ride_rides_ride_id_book_post

        Book Ride
        """
        pass

    def test_create_driver_drivers_post(self) -> None:
        """Test case for create_driver_drivers_post

        Create Driver
        """
        pass

    def test_create_ride_rides_post(self) -> None:
        """Test case for create_ride_rides_post

        Create Ride
        """
        pass

    def test_read_bookings_bookings_get(self) -> None:
        """Test case for read_bookings_bookings_get

        Read Bookings
        """
        pass

    def test_read_rides_rides_get(self) -> None:
        """Test case for read_rides_rides_get

        Read Rides
        """
        pass


if __name__ == '__main__':
    unittest.main()
