# coding: utf-8

"""
    Ride-Sharing API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ride import Ride

class TestRide(unittest.TestCase):
    """Ride unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Ride:
        """Test Ride
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Ride`
        """
        model = Ride()
        if include_optional:
            return Ride(
                driver_name = '',
                total_seats = 56,
                pickup_location = '',
                destination = '',
                id = 56,
                available_seats = 56
            )
        else:
            return Ride(
                driver_name = '',
                total_seats = 56,
                pickup_location = '',
                destination = '',
                id = 56,
                available_seats = 56,
        )
        """

    def testRide(self):
        """Test Ride"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
