"""Add User model and update Driver/Booking v2

Revision ID: 3fcf221c6f17
Revises: 822cadaf1be6
Create Date: 2026-04-20 14:09:18.102517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fcf221c6f17'
down_revision: Union[str, Sequence[str], None] = '822cadaf1be6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride_bookings', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_ride_bookings_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ride_bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
